function []=plotHypoAdj(FileName)
%% PLOTHYPOADJ: read a file generated by logVelest.sh --> *.HypoAdj
%   Input file should be *HypoCorr one (generated by 'vel2mat.sh')
%   USAGE: []=PLOTHYPOADJ(FileName)
%   AUTHOR: Matteo Bagagli @ ETH-Zurich
%

%    VELEST2MAT: collection of bash-script/Matlab functions for 
%                plotting VELEST v4.5 results.
%    Copyright (C) 2018  Matteo Bagagli
%
%    This program is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    This program is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with this program.  If not, see <http://www.gnu.org/licenses/>.

%% LOAD 
fid=fopen(FileName);
HYPO=textscan(fid,'%f %f %f %f'); % "%*f" --> skip a value
fclose(fid);

TIME=HYPO{1};
XX=HYPO{2};
YY=HYPO{3};
ZZ=HYPO{4};

%% PLOT
hold on
yyaxis left
h1=stem(XX,'k');
h2=stem(YY,'color',[0 0.75 0.1]);
h3=stem(ZZ,'b');
ylabel('Space (km)')
ylim([-0.5 0.5])
yyaxis right
h4=stem(TIME,'filled');
ylim([-0.5 0.5])
ylabel('Time (s)')
hold off
xlabel('Iteration')

%% DECORATOR
legend([h1,h2,h3,h4],{'x','y','z','t'})
set(gca,'xtick',0:length(TIME))

end