function []=plotRMS(FileName)
%% PLOTRMS: plot RMS value of velest run
%   The input file should be *.RMS (generated by 'vel2mat.sh')
%   USAGE: []=PLOTHYPOADJ(FileName)
%   AUTHOR: Matteo Bagagli @ ETH-Zurich
%

%    VELEST2MAT: collection of bash-script/Matlab functions for 
%                plotting VELEST v4.5 results.
%    Copyright (C) 2018  Matteo Bagagli
%
%    This program is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    This program is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with this program.  If not, see <http://www.gnu.org/licenses/>.

%% LOAD
RMS=load(FileName);

%% PLOT
% stem(RMS,'filled')
plot(RMS)
ylim([0 1])
ylabel('RMS (s)')
xlabel('Iteration')
set(gca,'YAxisLocation','right')
set(gca,'xtick',0:length(RMS))
